name: component-tests-deploy-action

description: Deploys Component Tests report packages to S3

inputs:
  project:
    description: ID of your project
    required: true
  github-token:
    description: PAT of a GitHub user which maintains PR's deploy comment
    required: true
  s3-key-id:
    description: S3 key ID
    required: true
  s3-secret-key:
    description: S3 secret key
    required: true

runs:
  using: composite
  steps:
  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
      github-token: ${{ inputs.github-token }}
      run-id: ${{ github.event.workflow_run.id }}
  - name: Extract PR Number
    id: pr
    run: echo "::set-output name=id::$(<pr/pr-id.txt)"
    shell: bash
  - name: Upload to S3
    uses: gravity-ui/upload-to-s3-action@v1
    with:
      src-path: playwright-report
      dest-path: /${{ inputs.project }}/pulls/${{ steps.pr.outputs.id }}/
      bucket: playwright-reports
      endpoint-url: https://storage.yandexcloud.net
      s3-key-id: ${{ inputs.s3-key-id }}
      s3-secret-key: ${{ inputs.s3-secret-key }}
      region: ru-central1
  - name: Create Comment
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      number: ${{ steps.pr.outputs.id }}
      message: '🎭 [Component Tests Report](https://storage.yandexcloud.net/playwright-reports/${{ inputs.project }}/pulls/${{ steps.pr.outputs.id }}/index.html) is ready.'